<?php

namespace CoreBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * Class Role
 * @package CoreBundle\Entity
 * @ORM\Table(name="role")
 */
class Role extends AutoGeneratedIdEntity
{
    /**
     * @var string
     * @ORM\Column(name="name", type="string", nullable=false)
     */
    private $name;

    /**
     * @var ArrayCollection
     * 
     * @ManyToOne(targetEntity="RolePermission")
     * @JoinColumn(name="role_id", referencedColumnName="id")
     */
    private $permissions;

    public function __construct()
    {
        $this->permissions = new ArrayCollection();
    }

    public function getName() : string
    {
        return $this->name;
    }

    public function setName(string $name) : Role
    {
        $this->name = $name;

        return $this;
    }

    public function getPermissions() : ArrayCollection
    {
        return $this->permissions;
    }

    public function addPermission(RolePermission $permission) : Role
    {
        $this->permissions->add($permission);

        return $this;
    }

    public function setPermissions(ArrayCollection $permissions) : Role
    {
        $this->permissions = $permissions;

        return $this;
    }
}